language: cpp

os:
  - linux
  - osx

sudo: false

compiler:
 - clang

env:
  matrix:
   - CONFIGURATION=Release
   - CONFIGURATION=Debug

addons:
  postgresql: "9.3"

before_install:
 - true

install:
 # TODO - get postgis working
 - true

before_script:
 - cd ..
 - git init .
 - git remote add origin http://github.com/mapnik/mapnik
 - git fetch
 - git checkout master
 - cd mapnik-gyp

script:
 - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
 - if [[ ${COMMIT_MESSAGE} =~ "[build]" ]]; then . build.sh; fi;
